.\"=====================================================================
.TH MKSLACK 1 "February 2011" "mkslack-3.8" ""
.\"=====================================================================
.SH NAME
mkslack \- a SlackBuild generator
.\"=====================================================================
.SH SYNOPSIS
.B mkslack
.RI [ options ]
.I archive
.\"=====================================================================
.SH DESCRIPTION
.B Mkslack
is a slackbuild generator which uses templates stored in
.I /usr/\:share/\:mkslack/\:templates
and a configuration file,
.IR /etc/\:mkslack/\:mkslack.conf ,
which you must edit to use your name, email, etc.
.SS Idea for use:
Create a directory, download the archive of a package into it, and run
.B mkslack
on it.
The initial slackbuild and info file are built by this script and, when
a test build/install is done and working, the files should be tweaked by
hand.
Especially don't forget to fill in the rest of the details in the info
file.
One thing to point out is that
.B mkslack
will overwrite these files if run again unless you keep the default
``KEEPBACKUPS=\:"YES"'' in the configuration file.
.PP
This is only a starter kit!
You
.B ARE
expected to edit the created files by hand afterwards to remove
unnecessary parts or add anything missing!
.\"=====================================================================
.SH OPTIONS
.\"---------------------------------------------------------------------
.TP
.BR \-h ", " \-\-help
Print the usage message to standard output.
.\"---------------------------------------------------------------------
.TP
.BR \-b ", " \-\-build
Run the SlackBuild after creation.
Got root?
.\"---------------------------------------------------------------------
.TP
.BR \-i ", " \-\-install
Install the package after running
.BR mkslack .
(Implies
.BR \-b .)
.\"---------------------------------------------------------------------
.TP
.BR \-v ", " \-\-version
Print the version of
.B mkslack
to standard output.
.\"---------------------------------------------------------------------
.TP
.BR \-V ", " \-\-ckver
Check for a new version of
.BR mkslack .
(Requires
.BR finger (1)
and internet access.)
.\"---------------------------------------------------------------------
.SS Configuration File Variables
.PP
.B NAME
and
.B EMAIL
should be set to what should appear in the SlackBuild and info files.
They default to empty strings and must be set to non-empty strings.
.PP
.B TAG
should be set to your custom tag (if any).
It defaults to ``_SBo''.
.PP
.B KEEPBACKUPS
may be set to ``YES'' or ``NO''.
If set to ``YES'', up to 5 backups of SlackBuilds and other files will
be kept.
The higher the number, the older they are.
It defaults to ``YES''.
.PP
.B ERRORACTION
specifies what to do on build errors caused by non-Slackware-standard
man or info pages and may be set to ``PROMPT'', ``AUTO'', or ``EXIT''.
If set to ``AUTO'' or set to ``PROMPT'' and answering ``y'' to the
resulting prompt,
.B mkslack
will adjust the SlackBuild to try to move the man and/or info pages from
.I /usr/share/{man,info}
to
.I /usr/{man,info}
and will rebuild.
If set to ``EXIT'' or set to ``PROMPT'' and answering ``n'',
.B mkslack
will exit.
It is also used to determine if
.B mkslack
should prompt the user to continue after producing output for the user
to read.
If set to ``AUTO'' or ``EXIT'',
.B mkslack
will not pause after output.
It defaults to ``PROMPT''.
.\"---------------------------------------------------------------------
.SS Command Line Variables
.PP
.BR DOCS ,
.BR BUILD ,
.BR ARCH ,
and
.B TAG
can all be adjusted at runtime by prefixing an assignment to one or more
of these variables on
.BR mkslack 's
command line.
.PP
.B DOCS
can adjust the list of documents in the top level of the source tree.
For example:
.IP
.nf
\fcDOCS=\fISomeFile\fP mkslack \fIarchive\fP
.fi
.PP
This will add ``SomeFile'' to the list.
For the default, see the assignment in
.BR mkslack ,
itself.
Depending on
.BR mkslack 's
location and your privileges, you may also edit the
.B DOCS
list there.
Any docs that aren't found will be removed from the list.
.PP
.B BUILD
can be used to increment the build number.
If it is not set, it defaults to 1.
.PP
.B ARCH
can be manually assigned.
It defaults to the auto-detected value of the architecture
.B mkslack
is running under, which is detected with
.BR uname (1).
.PP
.B TAG
can also be used to assign any value desired.
It defaults to ``_SBo''.
.\"=====================================================================
.SH FILES
.TP
.I /etc/mkslack/mkslack.conf
Main configuration file.
.TP
.I /usr/share/mkslack/templates/*
Template files used to generate the SlackBuilds for the various build
systems.
.\"=====================================================================
.SH AUTHORS
David Woodfall and slakmagik
.\"=====================================================================
.SH BUGS
Maybe.
Please send bug reports to dave@dawoodfall.net
.\"=====================================================================
.SH SEE ALSO
.BR finger (1),
.BR uname (1),
.BR upgradepkg (8)
.\" vim:set tw=72:
