#!/bin/sh

script=${0##*/}
ver=$1
# path vars that may be changed (repo and wherever pkg will end up must exist)
repo=/home/j/Projects/mkslack
build_dir=/tmp/mkslack-build
output=/tmp
pkg=$output/mkslack-$ver-noarch-1_daw.tgz

ck_dir() {
    for d in "$@"; do
        if [ ! -d $d ]; then
            mkdir -p $d || exit 1
        fi
    done
}

if [ $(id -u) -ne 0 ]; then
    echo "$script: need root." >&2
    exit 1
fi

if [ $# -ne 1 ]; then
    echo "$script: need a version argument." >&2
    exit 1
fi

ck_dir $build_dir $output

cd $repo && git archive --prefix=mkslack-$ver/ HEAD |
    gzip -9 > $build_dir/mkslack-$ver.tar.gz
cp mkslack.SlackBuild slack-desc doinst.sh $build_dir

# VERSION in the SlackBuild should be set properly as a general rule but
# during testing everything may not be just exactly perfect, so we pass it in
# from here.
cd $build_dir && VERSION=$ver sh ./mkslack.SlackBuild

if [ -f $pkg ]; then
    printf "Install/upgrade the mkslack package? "
    read REPLY
    if [ $REPLY = "y" ]; then
        cd $output && upgradepkg --install-new $pkg
    fi
else
    echo "$script: no package found." >&2
    exit 1
fi
